require File.join(File.dirname(__FILE__), "/assets/scss/utilities/list-files.rb")
http_path = "/"
css_dir = "assets/css"
sass_dir = "assets/scss"
images_dir = "assets/images"
javascripts_dir = "assets/js"
output_style = :compressed
relative_assets = true
line_comments = false
preferred_syntax = :scss